title: Tawilis Bioinformatics
description: Bioinformatics notebook for the tawilis multi-omics project.
theme: just-the-docs

url: https://meruila.github.io/tawilis-bioinfo/
enable_copy_code_button: true
favicon_ico: "./assets/images/favicon.ico"
logo: "./assets/images/tawilis_omics.png"

aux_links:
  "View on GitHub":
    - "https://github.com/meruila/tawilis-bioinfo"

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red